// <auto-generated />
using System;
using DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(HMDbContext))]
    [Migration("20241110234430_HomeNameChanges")]
    partial class HomeNameChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-rc.1.24451.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessLogic.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RUT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValidatorModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("BusinessLogic.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeviceType")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Devices");

                    b.HasDiscriminator<int>("DeviceType").HasValue(1);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BusinessLogic.Entities.Home", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HomeOwner")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MemberCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Homes");
                });

            modelBuilder.Entity("BusinessLogic.Entities.HomeDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HardwareId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("State")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("HomeId");

                    b.HasIndex("RoomId");

                    b.ToTable("HomeDevices");
                });

            modelBuilder.Entity("BusinessLogic.Entities.MemberSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.ToTable("MemberSettings");
                });

            modelBuilder.Entity("BusinessLogic.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Event")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("HardwareId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HomeDeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HomeDeviceId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("BusinessLogic.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a6b8ddf-3f92-4fda-87a4-777777777777"),
                            Value = "CanAsociateDevices"
                        },
                        new
                        {
                            Id = new Guid("d47fa8f6-ace7-42e5-8bdf-888888888888"),
                            Value = "CanListDevices"
                        },
                        new
                        {
                            Id = new Guid("2ebd4f21-3cd4-431f-97e7-999999999999"),
                            Value = "CanGetNotifications"
                        },
                        new
                        {
                            Id = new Guid("3bcde1b8-5ad2-4f6c-92c7-101010101010"),
                            Value = "CanAddMembers"
                        },
                        new
                        {
                            Id = new Guid("4c6b8b8d-3f92-4fda-87a4-202020202020"),
                            Value = "CanCreateRoom"
                        },
                        new
                        {
                            Id = new Guid("5d7fa8f6-ace7-42e5-8bdf-303030303030"),
                            Value = "CanAsociateDeviceToRoom"
                        },
                        new
                        {
                            Id = new Guid("6ebd4f21-3cd4-431f-97e7-404040404040"),
                            Value = "CanChangeHomeName"
                        },
                        new
                        {
                            Id = new Guid("7bcde1b8-5ad2-4f6c-92c7-505050505050"),
                            Value = "CanChangeHomeDevicesNames"
                        });
                });

            modelBuilder.Entity("BusinessLogic.Entities.PermissionKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PermissionKeys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Value = "CanCreateAdmin"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Value = "CanCreateCompanyOwner"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Value = "CanCreateHomeOwner"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Value = "CanCreateCompany"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Value = "CanCreateADevice"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Value = "CanManageUsers"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Value = "CanGetCompanies"
                        });
                });

            modelBuilder.Entity("BusinessLogic.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9a4a8f5-4393-4b5e-8c57-e7f5f58a9a61"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("6d72b33a-582b-411e-a9b1-333333333333"),
                            Name = "HomeOwner"
                        },
                        new
                        {
                            Id = new Guid("78947c68-f0aa-49d3-8f47-444444444444"),
                            Name = "CompanyOwner"
                        });
                });

            modelBuilder.Entity("BusinessLogic.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("BusinessLogic.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompanyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("HomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RoleID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.HasIndex("RoleID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b4a6e6cd-856e-4ad1-a87e-9f1b24d40a74"),
                            CreatedAt = new DateTime(2024, 11, 10, 20, 44, 28, 597, DateTimeKind.Local).AddTicks(2692),
                            Email = "admin@admin.com",
                            ImagePath = "",
                            LastName = "Admin",
                            Name = "Admin",
                            Password = "admin",
                            RoleID = new Guid("c9a4a8f5-4393-4b5e-8c57-e7f5f58a9a61")
                        });
                });

            modelBuilder.Entity("MemberSettingPermission", b =>
                {
                    b.Property<Guid>("MemberSettingsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MemberSettingsId", "PermissionsId");

                    b.HasIndex("PermissionsId");

                    b.ToTable("MemberSettingPermission");
                });

            modelBuilder.Entity("PermissionKeyRole", b =>
                {
                    b.Property<Guid>("PermissionKeysId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RolesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PermissionKeysId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("PermissionKeyRole");

                    b.HasData(
                        new
                        {
                            PermissionKeysId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RolesId = new Guid("c9a4a8f5-4393-4b5e-8c57-e7f5f58a9a61")
                        },
                        new
                        {
                            PermissionKeysId = new Guid("66666666-6666-6666-6666-666666666666"),
                            RolesId = new Guid("c9a4a8f5-4393-4b5e-8c57-e7f5f58a9a61")
                        },
                        new
                        {
                            PermissionKeysId = new Guid("22222222-2222-2222-2222-222222222222"),
                            RolesId = new Guid("c9a4a8f5-4393-4b5e-8c57-e7f5f58a9a61")
                        },
                        new
                        {
                            PermissionKeysId = new Guid("77777777-7777-7777-7777-777777777777"),
                            RolesId = new Guid("c9a4a8f5-4393-4b5e-8c57-e7f5f58a9a61")
                        },
                        new
                        {
                            PermissionKeysId = new Guid("44444444-4444-4444-4444-444444444444"),
                            RolesId = new Guid("78947c68-f0aa-49d3-8f47-444444444444")
                        },
                        new
                        {
                            PermissionKeysId = new Guid("55555555-5555-5555-5555-555555555555"),
                            RolesId = new Guid("78947c68-f0aa-49d3-8f47-444444444444")
                        },
                        new
                        {
                            PermissionKeysId = new Guid("33333333-3333-3333-3333-333333333333"),
                            RolesId = new Guid("6d72b33a-582b-411e-a9b1-333333333333")
                        });
                });

            modelBuilder.Entity("BusinessLogic.Entities.Camera", b =>
                {
                    b.HasBaseType("BusinessLogic.Entities.Device");

                    b.Property<bool>("Indoors")
                        .HasColumnType("bit");

                    b.Property<bool>("Outdoors")
                        .HasColumnType("bit");

                    b.Property<bool>("SupportMovementDetection")
                        .HasColumnType("bit");

                    b.Property<bool>("SupportPersonDetection")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("BusinessLogic.Entities.Company", b =>
                {
                    b.HasOne("BusinessLogic.Entities.User", "Owner")
                        .WithOne("Company")
                        .HasForeignKey("BusinessLogic.Entities.Company", "OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("BusinessLogic.Entities.Device", b =>
                {
                    b.HasOne("BusinessLogic.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("BusinessLogic.Entities.Home", b =>
                {
                    b.HasOne("BusinessLogic.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("BusinessLogic.Entities.HomeDevice", b =>
                {
                    b.HasOne("BusinessLogic.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLogic.Entities.Home", null)
                        .WithMany("Devices")
                        .HasForeignKey("HomeId");

                    b.HasOne("BusinessLogic.Entities.Room", null)
                        .WithMany("Devices")
                        .HasForeignKey("RoomId");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("BusinessLogic.Entities.MemberSetting", b =>
                {
                    b.HasOne("BusinessLogic.Entities.Home", null)
                        .WithMany("MemberSettings")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BusinessLogic.Entities.Notification", b =>
                {
                    b.HasOne("BusinessLogic.Entities.HomeDevice", "HomeDevice")
                        .WithMany()
                        .HasForeignKey("HomeDeviceId");

                    b.HasOne("BusinessLogic.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeDevice");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessLogic.Entities.Room", b =>
                {
                    b.HasOne("BusinessLogic.Entities.Home", null)
                        .WithMany("Rooms")
                        .HasForeignKey("HomeId");
                });

            modelBuilder.Entity("BusinessLogic.Entities.User", b =>
                {
                    b.HasOne("BusinessLogic.Entities.Home", null)
                        .WithMany("Members")
                        .HasForeignKey("HomeId");

                    b.HasOne("BusinessLogic.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MemberSettingPermission", b =>
                {
                    b.HasOne("BusinessLogic.Entities.MemberSetting", null)
                        .WithMany()
                        .HasForeignKey("MemberSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLogic.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PermissionKeyRole", b =>
                {
                    b.HasOne("BusinessLogic.Entities.PermissionKey", null)
                        .WithMany()
                        .HasForeignKey("PermissionKeysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLogic.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BusinessLogic.Entities.Home", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("MemberSettings");

                    b.Navigation("Members");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("BusinessLogic.Entities.Room", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("BusinessLogic.Entities.User", b =>
                {
                    b.Navigation("Company")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
