// <auto-generated />
using System;
using DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(HMDbContext))]
    [Migration("20241003192933_TestingCompanyMigration2")]
    partial class TestingCompanyMigration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-rc.1.24451.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RUT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Domain.Home", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Devices")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("HomeOwner")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MemberCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Homes");
                });

            modelBuilder.Entity("Domain.MemberSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.ToTable("MemberSettings");
                });

            modelBuilder.Entity("Domain.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7fa6a0f4-d7d9-4c89-a85e-92b937fc0274"),
                            Value = "CanAsociateDevices"
                        },
                        new
                        {
                            Id = new Guid("4d99af50-c4b9-4bc7-8c63-6e4f6f24a73a"),
                            Value = "CanListDevices"
                        },
                        new
                        {
                            Id = new Guid("c0f0d7a7-3e77-4128-87d3-30113b19936d"),
                            Value = "CanGetNotifications"
                        },
                        new
                        {
                            Id = new Guid("b2ff8154-fdb0-4a87-a7b5-ded13fb66f57"),
                            Value = "CanAddMembers"
                        });
                });

            modelBuilder.Entity("Domain.PermissionKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PermissionKeys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b4a6e6cd-856e-4ad1-a87e-9f1b24d40a74"),
                            Value = "CanCreateAdmin"
                        },
                        new
                        {
                            Id = new Guid("e43167ad-158b-4a39-8f5d-c0a69b32d7cf"),
                            Value = "CanCreateCompanyOwner"
                        },
                        new
                        {
                            Id = new Guid("c9a4a8f5-4393-4b5e-8c57-e7f5f58a9a61"),
                            Value = "CanCreateHomeOwner"
                        },
                        new
                        {
                            Id = new Guid("7fa6a0f4-d7d9-4c89-a85e-92b937fc0274"),
                            Value = "CanCreateCompany"
                        });
                });

            modelBuilder.Entity("Domain.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b4a6e6cd-856e-4ad1-a87e-9f1b24d40a74"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("e43167ad-158b-4a39-8f5d-c0a69b32d7cf"),
                            Name = "HomeOwner"
                        },
                        new
                        {
                            Id = new Guid("c9a4a8f5-4393-4b5e-8c57-e7f5f58a9a61"),
                            Name = "CompanyOwner"
                        });
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompanyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("HomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RoleID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyID")
                        .IsUnique()
                        .HasFilter("[CompanyID] IS NOT NULL");

                    b.HasIndex("HomeId");

                    b.HasIndex("RoleID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b4a6e6cd-856e-4ad1-a87e-9f1b24d40a74"),
                            Email = "admin@admin.com",
                            ImagePath = "",
                            LastName = "Admin",
                            Name = "Admin",
                            Password = "admin",
                            RoleID = new Guid("b4a6e6cd-856e-4ad1-a87e-9f1b24d40a74")
                        },
                        new
                        {
                            Id = new Guid("e43167ad-158b-4a39-8f5d-c0a69b32d7cf"),
                            Email = "homeowner1@gmail.com",
                            ImagePath = "",
                            LastName = "HomeOwner",
                            Name = "HomeOwner",
                            Password = "homeowner@1",
                            RoleID = new Guid("e43167ad-158b-4a39-8f5d-c0a69b32d7cf")
                        },
                        new
                        {
                            Id = new Guid("c9a4a8f5-4393-4b5e-8c57-e7f5f58a9a61"),
                            Email = "companyowner1@gmail.com",
                            ImagePath = "",
                            LastName = "CompanyOwner",
                            Name = "CompanyOwner",
                            Password = "companyowner@1",
                            RoleID = new Guid("c9a4a8f5-4393-4b5e-8c57-e7f5f58a9a61")
                        });
                });

            modelBuilder.Entity("MemberSettingPermission", b =>
                {
                    b.Property<Guid>("MemberSettingsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MemberSettingsId", "PermissionsId");

                    b.HasIndex("PermissionsId");

                    b.ToTable("MemberSettingPermissions", (string)null);
                });

            modelBuilder.Entity("PermissionKeyRole", b =>
                {
                    b.Property<Guid>("PermissionKeysId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RolesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PermissionKeysId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("PermissionKeyRole");

                    b.HasData(
                        new
                        {
                            PermissionKeysId = new Guid("b4a6e6cd-856e-4ad1-a87e-9f1b24d40a74"),
                            RolesId = new Guid("b4a6e6cd-856e-4ad1-a87e-9f1b24d40a74")
                        },
                        new
                        {
                            PermissionKeysId = new Guid("e43167ad-158b-4a39-8f5d-c0a69b32d7cf"),
                            RolesId = new Guid("b4a6e6cd-856e-4ad1-a87e-9f1b24d40a74")
                        },
                        new
                        {
                            PermissionKeysId = new Guid("c9a4a8f5-4393-4b5e-8c57-e7f5f58a9a61"),
                            RolesId = new Guid("e43167ad-158b-4a39-8f5d-c0a69b32d7cf")
                        },
                        new
                        {
                            PermissionKeysId = new Guid("7fa6a0f4-d7d9-4c89-a85e-92b937fc0274"),
                            RolesId = new Guid("c9a4a8f5-4393-4b5e-8c57-e7f5f58a9a61")
                        });
                });

            modelBuilder.Entity("Domain.Home", b =>
                {
                    b.HasOne("Domain.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Domain.MemberSetting", b =>
                {
                    b.HasOne("Domain.Home", null)
                        .WithMany("MemberSettings")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.HasOne("Domain.Company", "Company")
                        .WithOne("Owner")
                        .HasForeignKey("Domain.User", "CompanyID");

                    b.HasOne("Domain.Home", null)
                        .WithMany("Members")
                        .HasForeignKey("HomeId");

                    b.HasOne("Domain.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID");

                    b.Navigation("Company");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MemberSettingPermission", b =>
                {
                    b.HasOne("Domain.MemberSetting", null)
                        .WithMany()
                        .HasForeignKey("MemberSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PermissionKeyRole", b =>
                {
                    b.HasOne("Domain.PermissionKey", null)
                        .WithMany()
                        .HasForeignKey("PermissionKeysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Company", b =>
                {
                    b.Navigation("Owner")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Home", b =>
                {
                    b.Navigation("MemberSettings");

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
